### ISSUE TITLE
Docker is showing as down for Ubuntu even though it isn't

### ISSUE THREAD

**Issue by rpsedlak** [rpsedlak/zabbix-docker#23]
Ubuntu runs docker with a daemon parameter instead of a -d parameter.

**Comment by rpsedlak** [comment]
Added separate process counters for CentOS and Ubuntu.  Adjusted the trigger calculations as well.

**Comment by xelexin** [comment]
On ubuntu 16.04 I had information that docker is down.
I fix the userparameter_zabbixdocker.conf. Changed ubuntu line "docker daemon" with "dockerd".
