### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by andyChenn** [rpsedlak/zabbix-docker#31]
when it runing, i found a problem like Value should be a JSON object.
the key is "docker.discovery".

but i run the zabbix-docker-discover.py then return the result is ::

{
    "data": [
        {
            "{#ZD_NAME}": "k8s_elasticsearch-logging.8878d4d1_elasticsearch-logging-v1-t6q2q_kube-system_7b229c21-0934-11e7-a9cb-005056953399_d7828d0a",
            "{#ZD_IMAGE}": "gcr.io/google-containers/elasticsearch:v2.4.1",
            "{#ZD_ID}": "2bffaa1eee77"
        },
        {
            "{#ZD_NAME}": "k8s_POD.72963366_elasticsearch-logging-v1-t6q2q_kube-system_7b229c21-0934-11e7-a9cb-005056953399_bcdb4c39",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "1c38f8363b62"
        },
        {
            "{#ZD_NAME}": "k8s_fluentd-elasticsearch.6680f463_fluentd-elasticsearch-bhdr0_kube-system_aaa814c2-0932-11e7-a9cb-005056953399_89b1e4a1",
            "{#ZD_IMAGE}": "gcr.io/google-containers/fluentd-elasticsearch:1.20",
            "{#ZD_ID}": "8c3033625f37"
        },
        {
            "{#ZD_NAME}": "k8s_POD.ae8ee9ac_fluentd-elasticsearch-bhdr0_kube-system_aaa814c2-0932-11e7-a9cb-005056953399_fbedc160",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "d53c7fe8c219"
        },
        {
            "{#ZD_NAME}": "k8s_saas-customer.4073ca31_saas-customer-7vhoo_saas_ce1b4fa1-091a-11e7-a9cb-005056953399_72158ef8",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saas-customer:0.10.1",
            "{#ZD_ID}": "49afe5e4ae89"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saas-customer-7vhoo_saas_ce1b4fa1-091a-11e7-a9cb-005056953399_015de107",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "786448301d39"
        },
        {
            "{#ZD_NAME}": "k8s_saas-settings.38d7ca2f_saas-settings-i0zca_saas_11be1ce7-f74b-11e6-909c-005056953399_0ebc5054",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saas-settings:0.10.2",
            "{#ZD_ID}": "48064ad250aa"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saas-settings-i0zca_saas_11be1ce7-f74b-11e6-909c-005056953399_6e5c97cf",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "dbcc937a39b0"
        },
        {
            "{#ZD_NAME}": "k8s_saasclient.b7d7e8ac_saasclient-tsei1_saas_ae8a06cd-058d-11e7-909c-005056953399_eca19b1f",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saasclient:0.10.7",
            "{#ZD_ID}": "590c6b44de86"
        },
        {
            "{#ZD_NAME}": "k8s_saas-contact-history.b9f4d2bf_saas-contact-history-xe2g2_saas_1184aa0e-f74b-11e6-909c-005056953399_2eff55ef",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saas-contact-history:0.10.3.3",
            "{#ZD_ID}": "5582d1be21e8"
        },
        {
            "{#ZD_NAME}": "k8s_redis.c9a30fbb_redis-6yui2_default_e7c17e81-d7d8-11e6-909c-005056953399_845bd7c0",
            "{#ZD_IMAGE}": "redis:3.2.0-alpine",
            "{#ZD_ID}": "a69442c4fe07"
        },
        {
            "{#ZD_NAME}": "k8s_ces.3c1bd515_ces-0rtgx_ces_62616e2e-dbcf-11e6-909c-005056953399_185b57ca",
            "{#ZD_IMAGE}": "registry:5000/wecloud/ces-proxy",
            "{#ZD_ID}": "8a38af7f89c9"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saas-contact-history-xe2g2_saas_1184aa0e-f74b-11e6-909c-005056953399_d960080a",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "1b3b635f5cc2"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saasclient-tsei1_saas_ae8a06cd-058d-11e7-909c-005056953399_7fe7fa21",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "cc22a378c9f2"
        },
        {
            "{#ZD_NAME}": "k8s_ivr.26c0999b_ivr-scpir_ces_bfffe2fd-d3c3-11e6-909c-005056953399_503e48fd",
            "{#ZD_IMAGE}": "registry:5000/wecloud/ivr-web",
            "{#ZD_ID}": "7996e214bf06"
        },
        {
            "{#ZD_NAME}": "k8s_POD.21290ba7_ces-0rtgx_ces_62616e2e-dbcf-11e6-909c-005056953399_11f61ce8",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "4f24d190ebf4"
        },
        {
            "{#ZD_NAME}": "k8s_POD.10ef0dc9_redis-6yui2_default_e7c17e81-d7d8-11e6-909c-005056953399_fad3b1cc",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "e5b15ca966ad"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_ivr-scpir_ces_bfffe2fd-d3c3-11e6-909c-005056953399_cbc11d2f",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "4941ed91d438"
        },
        {
            "{#ZD_NAME}": "k8s_saas-settings.38d7ca2f_saas-settings-i0zca_saas_11be1ce7-f74b-11e6-909c-005056953399_44105ec5",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saas-settings:0.10.2",
            "{#ZD_ID}": "63946569b3c1"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saas-settings-i0zca_saas_11be1ce7-f74b-11e6-909c-005056953399_02848409",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "643a4370a540"
        },
        {
            "{#ZD_NAME}": "k8s_saasclient.b7d7e8ac_saasclient-tsei1_saas_ae8a06cd-058d-11e7-909c-005056953399_7c9d251a",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saasclient:0.10.7",
            "{#ZD_ID}": "72d4017e22cd"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saasclient-tsei1_saas_ae8a06cd-058d-11e7-909c-005056953399_5444bc8c",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "1a9cf3028f0e"
        },
        {
            "{#ZD_NAME}": "k8s_ces.3c1bd515_ces-0rtgx_ces_62616e2e-dbcf-11e6-909c-005056953399_2be6098e",
            "{#ZD_IMAGE}": "registry:5000/wecloud/ces-proxy",
            "{#ZD_ID}": "c1c71de926f9"
        },
        {
            "{#ZD_NAME}": "k8s_saas-contact-history.b9f4d2bf_saas-contact-history-xe2g2_saas_1184aa0e-f74b-11e6-909c-005056953399_ed582b9e",
            "{#ZD_IMAGE}": "registry:5000/wecloud/saas-contact-history:0.10.3.3",
            "{#ZD_ID}": "20ede76bf7e7"
        },
        {
            "{#ZD_NAME}": "k8s_redis.c9a30fbb_redis-6yui2_default_e7c17e81-d7d8-11e6-909c-005056953399_e662f763",
            "{#ZD_IMAGE}": "redis:3.2.0-alpine",
            "{#ZD_ID}": "b89d754065bc"
        },
        {
            "{#ZD_NAME}": "k8s_ivr.26c0999b_ivr-scpir_ces_bfffe2fd-d3c3-11e6-909c-005056953399_e6b68cd3",
            "{#ZD_IMAGE}": "registry:5000/wecloud/ivr-web",
            "{#ZD_ID}": "ad2b6752f9a9"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_saas-contact-history-xe2g2_saas_1184aa0e-f74b-11e6-909c-005056953399_0bafa2d6",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "6ff6773a9d61"
        },
        {
            "{#ZD_NAME}": "k8s_POD.24f70ba9_ivr-scpir_ces_bfffe2fd-d3c3-11e6-909c-005056953399_aa1d73a6",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "c381a99ccbef"
        },
        {
            "{#ZD_NAME}": "k8s_POD.21290ba7_ces-0rtgx_ces_62616e2e-dbcf-11e6-909c-005056953399_22032654",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "25ed31fa494a"
        },
        {
            "{#ZD_NAME}": "k8s_POD.10ef0dc9_redis-6yui2_default_e7c17e81-d7d8-11e6-909c-005056953399_7786f262",
            "{#ZD_IMAGE}": "registry.access.redhat.com/rhel7/pod-infrastructure:latest",
            "{#ZD_ID}": "8585c4d3157b"
        }
    ]
}

why it throw the exception "value should be a json objec"? what shall i do ?

**Comment by rpsedlak** [comment]
Andy,

I apologize that I just saw this.  The JSON object appears to be correct from what I can tell.

What version of Zabbix are you using?  What OS are you installed on?  What is the docker version that you are using?

I developed this module over a year ago so there will likely be some entropy due to version changes, etc.

Richard

**Comment by rpsedlak** [comment]
Spent a few hours testing this with CentOS 7.x, Ubuntu 14.04, and Ubuntu 16.04.  Could not reproduce.
