### ISSUE TITLE
Template error with Zabbix 5.2

### ISSUE THREAD

**Issue by carrieredaniel** [rpsedlak/zabbix-docker#45]
When installing the Template file on Zabbix 5.2 GUI, I get the following error:

Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "snmpv3_contextname" is missing. [conf.import.php:89 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → CXmlValidator->validate() → C30XmlValidator->validate() → CXmlValidatorGeneral->validate() → CXmlValidatorGeneral->validateData() → CXmlValidatorGeneral->validateData() → CXmlValidatorGeneral->validateData() → CXmlValidatorGeneral->validateData() → CXmlValidatorGeneral->validateData() in include/classes/import/validators/CXmlValidatorGeneral.php:168]

Need to add:
                    <snmpv3_contextname/>
                    <snmpv3_authprotocol/>
                    <snmpv3_privprotocol/>
                    <logtimefmt/>
on multiple places (after all <snmpv3_privpassphrase/>)

**Comment by Yarli** [comment]
I've fixed this issue in pull request #47 
Currently awaiting merge to master by author.

**Comment by rpsedlak** [comment]
Merged. Thanks for the contribution.
